'\" t
.\"     Title: script
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.26
.\"      Date: 2026-06-16
.\"    Manual: 用户命令
.\"    Source: util-linux 2.42.2
.\"  Language: Chinese (Simplified)
.\"
.TH "SCRIPT" "1" "2026-06-16" "util\-linux 2.42.2" "用户命令"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "名称"
script \- 制作终端会话的录本
.SH "概述"
.sp
\fBscript\fP [选项] [\fI文件\fP] [\fB\-\-\fP \fI命令\fP [\fI参数\fP.\|.\|.]]
.SH "描述"
.sp
\fBscript\fP 会录制终端会话中的所有内容。终端数据以原始形式存储到日志文件中，计时信息存储到另一个（可选的）结构化日志文件中。计时日志文件对于稍后通过 \fBscriptreplay\fP(1) 回放会话以及存储会话的附加信息是必需的。
.sp
自 2.35 版本起，\fBscript\fP 支持多流，允许将输入和输出记录到单独的文件或同一个文件中。此版本还支持一种新的计时文件，记录额外的信息。命令 \fBscriptreplay \-\-summary\fP 可以显示所有信息。
.sp
如果未指定文件名，对话将保存在文件 \fItypescript\fP 中。
.SH "选项"
.sp
\fB\-a\fP, \fB\-\-append\fP — 将输出追加到 \fI文件\fP 或 \fItypescript\fP，保留先前的内容。
.sp
\fB\-c\fP, \fB\-\-command\fP \fI命令\fP — 运行指定的 \fI命令\fP 而非交互式 shell。也可在双破折号 (\fB\-\-\fP) 之后指定 \fI命令\fP。
.sp
\fB\-E\fP, \fB\-\-echo\fP \fI模式\fP — 控制会话伪终端从端的 ECHO 标志。支持的模式为 \fIalways\fP、\fInever\fP 或 \fIauto\fP。默认为 \fIauto\fP。
.sp
\fB\-e\fP, \fB\-\-return\fP — 返回子进程的退出状态。信号终止时使用与 bash 相同的格式（退出状态为 128 + 信号编号）。
.sp
\fB\-f\fP, \fB\-\-flush\fP — 每次写入后刷新输出。适用于远程协作：一人执行 \fBmkfifo foo; script \-f foo\fP，另一人可以通过 \fBcat foo\fP 实时查看。
.sp
\fB\-B\fP, \fB\-\-log\-io\fP \fI文件\fP — 记录输入和输出到同一文件。
.sp
\fB\-I\fP, \fB\-\-log\-in\fP \fI文件\fP — 记录输入到指定文件。注意，这会记录所有输入，包括密码输入。
.sp
\fB\-O\fP, \fB\-\-log\-out\fP \fI文件\fP — 记录输出到指定文件。默认记录到 \fItypescript\fP。
.sp
\fB\-T\fP, \fB\-\-log\-timing\fP \fI文件\fP — 记录计时信息到文件。支持经典格式（单流）和高级多流格式。
.sp
\fB\-o\fP, \fB\-\-output\-limit\fP \fI大小\fP — 限制录本和计时文件的大小。
.sp
\fB\-q\fP, \fB\-\-quiet\fP — 静默模式，不将开始和完成消息写入标准输出。
.sp
\fB\-h\fP, \fB\-\-help\fP — 显示帮助文本并退出。
.sp
\fB\-V\fP, \fB\-\-version\fP — 显示版本信息并退出。
.SH "信号"
.sp
收到 \fBSIGUSR1\fP 时，\fBscript\fP 立即刷新输出文件。
.SH "环境变量"
.sp
\fBSHELL\fP — 如果设置了此变量，\fBscript\fP 将使用它作为 shell。如果未设置，则使用 Bourne shell。
.SH "参见"
.sp
\fBscriptreplay\fP(1), \fBscriptlive\fP(1)
.SH "报告错误"
.sp
请通过 \c
.URL "https://github.com/util\-linux/util\-linux/issues" "issue tracker" " 报告错误。"
.SH "[中文版最新更新]"
.BR 2026.07.12
.SH "[中文版维护人]"
.B Aurolystant
.SH "[中国 Linux 论坛中文手册页翻译计划]"
.BI https://github.com/man-pages-zh/manpages-zh
