.\"  Copyright (c) 1990-2009 Info-ZIP.  All rights reserved.
.\"
.\"  See the accompanying file LICENSE, version 2009-Jan-02 or later
.\"  (the contents of which are also included in unzip.h) for terms of use.
.\"  If, for some reason, all these files are missing, the Info-ZIP license
.\"  also may be found at:  ftp://ftp.info-zip.org/pub/infozip/license.html
.\"
.\" unzip.1 by Greg Roelofs, Fulvio Marino, Jim van Zandt and others.
.\"
.\" =========================================================================
.\" define .EX/.EE (for multiline user-command examples; normal Courier font)
.de EX
.in +4n
.nf
.ft CW
..
.de EE
.ft R
.fi
.in -4n
..
.\" =========================================================================
.TH UNZIP 1L "2009-04-20 (v6.0)" "Info-ZIP"
.SH 名称 (NAME)
unzip \- 列出、测试和提取 ZIP 归档文件中的压缩文件
.PD
.SH 概述 (SYNOPSIS)
\fBunzip\fP [\fB\-Z\fP] [\fB\-cflptTuvz\fP[\fBabjnoqsCDKLMUVWX$/:^\fP]]
\fIfile\fP[\fI.zip\fP] [\fIfile(s)\fP\ .\|.\|.]
[\fB\-x\fP\ \fIxfile(s)\fP\ .\|.\|.] [\fB\-d\fP\ \fIexdir\fP]
.PD
.\" =========================================================================
.SH 描述 (DESCRIPTION)
\fIunzip\fP 将列出、测试或从 ZIP 归档文件中提取文件，
ZIP 归档文件常见于 MS-DOS 系统。
默认行为（不带选项）是将指定 ZIP 归档中的所有文件提取到
当前目录（及其子目录）。
配套程序 \fIzip\fP(1L) 用于创建 ZIP 归档；
这两个程序都与 PKWARE 的 \fIPKZIP\fP 和 \fIPKUNZIP\fP
（用于 MS-DOS）创建的归档兼容，
但在许多情况下程序选项或默认行为有所不同。
.PD
.\" =========================================================================
.SH 参数 (ARGUMENTS)
.TP
.IR file [ .zip ]
ZIP 归档文件的路径。
如果文件规格是通配符，则每个匹配的文件按操作系统
（或文件系统）确定的顺序处理。
只有文件名可以是通配符；路径本身不能。
通配符表达式类似于常用 Unix shell
（\fIsh\fP、\fIksh\fP、\fIcsh\fP）中支持的语法，可以包含：
.RS
.IP *
匹配 0 个或多个字符的序列
.IP ?
匹配恰好 1 个字符
.IP [.\|.\|.]
匹配方括号内的任意单个字符；
范围由起始字符、连字符和结束字符指定。
如果左括号后跟感叹号或插入符（`!' 或 `^'），
则方括号内的字符范围被取反
（即匹配方括号内字符\fI之外\fP的任意字符）。
要指定字面上的左括号，
必须使用三字符序列 ``[[]''。
.RE
.IP
（请务必引用任何可能被操作系统解释或修改的字符，
特别是在 Unix 和 VMS 下。）
如果找不到匹配项，则假定规格是字面文件名；
如果仍然失败，则追加后缀 \fC.zip\fR。
请注意，自解压 ZIP 文件与任何其他 ZIP 归档一样受支持；
只需显式指定 \fC.exe\fR 后缀（如果有）。
.IP [\fIfile(s)\fP]
要处理的归档成员的可选列表，用空格分隔。
（使用 VMSCLI 定义编译的 VMS 版本必须用逗号分隔文件。
请参见下面的 \fBOPTIONS\fP 中的 \fB\-v\fP。）
可以使用正则表达式（通配符）匹配多个成员；参见上文。
再次提醒，请务必引用否则会被操作系统展开或修改的表达式。
.IP [\fB\-x\fP\ \fIxfile(s)\fP]
要从处理中排除的归档成员的可选列表。
由于通配符通常匹配（`/'）目录分隔符
（例外情况参见 \fB\-W\fP 选项），
此选项可用于排除子目录中的任何文件。
例如，``\fCunzip foo *.[ch] -x */*\fR'' 将提取主目录中
的所有 C 源文件，但不提取任何子目录中的文件。
如果没有 \fB\-x\fP 选项，
zip 文件中所有目录中的所有 C 源文件都将被提取。
.IP [\fB\-d\fP\ \fIexdir\fP]
提取文件的目标可选目录。
默认情况下，所有文件和子目录都在当前目录中重新创建；
\fB\-d\fP 选项允许提取到任意目录
（始终假设有权限写入该目录）。
此选项不必出现在命令行末尾；
它也可以在 zip 文件规格之前（与普通选项一起）、
zip 文件规格之后立即、
或在 \fIfile(s)\fP 和 \fB\-x\fP 选项之间被接受。
选项和目录可以连接在一起而不带任何空白，
但请注意这可能抑制正常的 shell 行为。
特别是，``\fC\-d\ ~\fR''（波浪号）被 Unix C shell
扩展为用户的主目录名，但 ``\fC\-d~\fR'' 被视为
当前目录的字面子目录 ``\fB~\fP''。
.\" =========================================================================
.SH 选项 (OPTIONS)
注意，为了支持过时的硬件，\fIunzip\fP 的使用屏幕限制为
22 或 23 行，因此应仅视为基本 \fIunzip\fP 语法的提醒，
而非所有可能标志的详尽列表。详尽的列表如下：
.TP
.B \-Z
\fIzipinfo\fP(1L) 模式。
如果命令行上的第一个选项是 \fB\-Z\fP，
则其余选项被视为 \fIzipinfo\fP(1L) 选项。
有关这些选项的描述，请参见相应的手册页。
.TP
.B \-A
[OS/2, Unix DLL] 打印 DLL 编程接口（API）的扩展帮助信息。
.TP
.B \-c
将文件提取到 stdout/屏幕（``CRT''）。
此选项类似于 \fB\-p\fP 选项，
但每个文件的名称在提取时会被打印，
\fB\-a\fP 选项被允许，
并且 ASCII-EBCDIC 转换会在适当时自动执行。
此选项未列在 \fIunzip\fP 的使用屏幕中。
.TP
.B \-f
刷新现有文件，即只提取那些已存在于磁盘上且比磁盘副本更新的文件。
默认情况下，\fIunzip\fP 在覆盖前会进行询问，
但可以使用 \fB\-o\fP 选项来抑制询问。
请注意，在许多操作系统下，必须正确设置 TZ（时区）环境变量，
\fB\-f\fP 和 \fB\-u\fP 才能正常工作
（在 Unix 下，该变量通常自动设置）。
其原因有些微妙，但与 DOS 格式的文件时间（始终为本地时间）和
Unix 格式的时间（始终为 GMT/UTC）之间的差异以及需要比较两者有关。
典型的 TZ 值是 ``PST8PDT''
（美国太平洋时间，夏令时或"夏季时间"自动调整）。
.TP
.B \-l
列出归档文件（短格式）。
打印指定文件的名称、未压缩的文件大小和修改日期时间，
以及所有指定文件的汇总。
如果 UnZip 编译时定义了 OS2_EAS，\fB\-l\fP 选项还会
列出存储的 OS/2 扩展属性（EA）和
OS/2 访问控制列表（ACL）的大小列。
此外，还会显示 zip 文件注释和单个文件注释（如果有）。
如果文件是从单大小写文件系统
（例如旧的 MS-DOS FAT 文件系统）归档的，
并且给出了 \fB\-L\fP 选项，
则文件名会被转换为小写并在前面加上插入符（^）。
.TP
.B \-p
将文件提取到管道（stdout）。
只有文件数据被发送到 stdout，
文件始终以二进制格式提取，与存储时完全一致（不进行转换）。
.TP
.B \-t
测试归档文件。
此选项在内存中提取每个指定文件，
并将扩展文件的 CRC（循环冗余校验，一种增强型校验和）
与原始文件存储的 CRC 值进行比较。
.TP
.B \-T
[大多数操作系统] 将归档的时间戳设置为每个归档中最新的文件的时间戳。
这对应于 \fIzip\fP 的 \fB\-go\fP 选项，
不同之处在于它可以用于通配符 zip 文件
（例如，``\fCunzip \-T \e*.zip\fR''）并且速度更快。
.TP
.B \-u
更新现有文件并创建不存在的文件。
此选项执行与 \fB\-f\fP 选项相同的功能，
提取（带询问）比磁盘上同名文件更新的文件，
此外它还提取磁盘上尚不存在的文件。
有关正确设置时区的信息，请参见上面的 \fB\-f\fP。
.TP
.B \-v
列出归档文件（详细格式）或显示诊断版本信息。
此选项已演变并作为选项和修饰符两者运行。
作为选项，它有两个目的：
当指定了 zip 文件而没有其他选项时，
\fB\-v\fP 详细列出归档文件，
在基本 \fB\-l\fP 信息的基础上增加了压缩方法、
压缩后大小、压缩率和 32 位 CRC。
与大多数竞争工具不同，\fIunzip\fP 从压缩大小数字中
移除加密条目的 12 个额外头字节。
因此，压缩大小和压缩率数字与条目的加密状态无关，
并显示正确的压缩性能。
（zip 文件条目加密压缩数据流的完整大小
由更详细的 \fIzipinfo\fP(1L) 报告，参见单独的手册。）
当没有指定 zip 文件时
（即完整命令仅为 ``\fCunzip \-v\fR''），
将打印诊断屏幕。
除了带有发布日期和版本的正常标题外，\fIunzip\fP 还列出
Info-ZIP 的 FTP 主页以及查找其他 FTP 和非 FTP 站点的位置；
编译的目标操作系统以及（可能还有）编译的硬件、
使用的编译器和版本以及编译日期；
任何可能影响程序操作的特殊编译选项
（另请参见下面的 \fBDECRYPTION\fP）；
以及可能同样影响程序的环境变量中存储的任何选项
（请参见下面的 \fBENVIRONMENT OPTIONS\fP）。
作为修饰符，它与其他选项（例如 \fB\-t\fP）配合使用
以产生更详细或调试输出；这尚未完全实现，但将在未来版本中完成。
.TP
.B \-z
仅显示归档注释。
.PD
.\" =========================================================================
.SH 修饰符 (MODIFIERS)
.TP
.B \-a
转换文本文件。
通常所有文件都完全按照存储方式提取（作为"二进制"文件）。
\fB\-a\fP 选项会导致被 \fIzip\fP 标识为文本文件的文件
（在 \fIzipinfo\fP 列表中带有 `t' 标签，而不是 `b' 的文件）
自动以文本方式提取，根据需要转换行尾、文件结束符和字符集本身。
（例如，Unix 文件使用换行符（LF）作为行尾（EOL）
且没有文件结束符（EOF）标记；
Macintosh 使用回车符（CR）作为 EOL；
大多数 PC 操作系统使用 CR+LF 作为 EOL
并使用 control-Z 作为 EOF。
此外，IBM 大型机和密歇根终端系统使用 EBCDIC
而非更常见的 ASCII 字符集，NT 支持 Unicode。）
请注意，\fIzip\fP 对文本文件的识别远非完美；
某些"文本"文件实际上可能是二进制文件，反之亦然。
因此，\fIunzip\fP 在使用 \fB\-a\fP 选项时，
会为每个提取的文件打印 ``\fC[text]\fR'' 或
``\fC[binary]\fR'' 作为视觉检查。
\fB\-aa\fP 选项强制将所有文件作为文本提取，
无论假定的文件类型如何。在 VMS 上，另请参见 \fB\-S\fP。
.TP
.B \-b
[通用] 将所有文件视为二进制文件（不进行文本转换）。
这是 \fB\-\-\-a\fP 的快捷方式。
.TP
.B \-b
[Tandem] 强制创建文件代码类型为 180（'C'）的文件，
当提取标记为"文本"的 Zip 条目时。
（在 Tandem 上，\fB\-a\fP 默认启用，见上文）。
.TP
.B \-b
[VMS] 自动将二进制文件（见上文 \fB\-a\fP）
转换为固定长度、512 字节的记录格式。
加倍选项（\fB\-bb\fP）强制所有文件以此格式提取。
当提取到标准输出时（\fB\-c\fP 或 \fB\-p\fP 选项生效），
文本记录分隔符的默认转换对于二进制（\fB\-b\fP）
或全部（\fB\-bb\fP）文件被禁用。
.TP
.B \-B
[编译时定义了 UNIXBACKUP 时启用]
保存每个被覆盖文件的备份副本。
备份文件获得目标文件的名称，
并附加波浪号及可选的唯一序列号（最多 5 位数字）。
当另一个具有原始名称加波浪号的文件已存在时，会应用序列号。
当与"覆盖所有"选项 \fB\-o\fP 一起使用时，
永远不会创建编号备份文件。在这种情况下，
所有备份文件都被命名为原始文件加波浪号，
现有的备份文件会被删除而不会通知。
此功能类似于许多环境下 \fIemacs\fP(1) 的默认行为。
.IP
示例：``\fCfoo\fR'' 的旧副本被重命名为 ``\fCfoo~\fR''。
.IP
警告：用户应意识到 \fB-B\fP 选项并不能在所有情况下
防止现有数据丢失。
例如，当 \fIunzip\fP 在覆盖所有模式下运行时，
现有的 ``\fCfoo~\fR'' 文件会在 \fIunzip\fP 尝试将
``\fCfoo\fR'' 重命名为 ``\fCfoo~\fR'' 之前被删除。
当此重命名尝试失败时（由于文件锁定、权限不足或其他原因），
``\fCfoo~\fR'' 的提取被取消，但旧的备份文件已经丢失。
当编号备份文件的序列号范围耗尽时
（99999，或 16 位系统为 65535）也会发生类似情况。
在这种情况下，具有最大序列号的备份文件会被删除并替换为
新的备份版本，而不会通知用户。
.TP
.B \-C
使用不区分大小写的匹配来选择命令行提取选择模式列表中的归档条目。
\fIunzip\fP 的理念是"问什么给什么"
（这也是 \fB\-L\fP/\fB\-U\fP 变更的原因；
请参见下面的相关选项）。
因为某些文件系统完全区分大小写
（特别是 Unix 操作系统下的文件系统），
并且因为 ZIP 归档和 \fIunzip\fP 本身都是跨平台可移植的，
\fIunzip\fP 的默认行为是区分大小写地匹配通配符和字面文件名。
也就是说，在命令行上指定 ``\fCmakefile\fR''
将\fI只\fP匹配归档中的 ``makefile''，
而不匹配 ``Makefile'' 或 ``MAKEFILE''
（通配符规格同理）。
由于这与许多其他操作系统/文件系统的行为不符
（例如 OS/2 HPFS，它保留混合大小写但对大小写不敏感），
\fB\-C\fP 选项可用于强制所有文件名匹配不区分大小写。
在上面的例子中，所有三个文件都将匹配
``\fCmakefile\fR''（或 ``\fCmake*\fR'' 等）。
\fB\-C\fP 选项影响正常文件列表和排除文件列表（xlist）中的文件规格。
.IP
请注意，\fB\-C\fP 选项既不影响 zip 文件的搜索，
也不影响归档条目与提取路径上现有文件的匹配。
在区分大小写的文件系统上，
当提取条目 ``foo'' 时，
\fIunzip\fP 绝不会尝试覆盖文件 ``FOO''！
.TP
.B \-D
跳过恢复提取项的时间戳。
通常，\fIunzip\fP 会尝试恢复 Zip 归档中提供的所有提取项的元信息
（不需要权限或不会造成安全风险的信息）。
通过指定 \fB\-D\fP，\fIunzip\fP 被告知抑制恢复
从 Zip 归档条目显式创建的目录的时间戳。
此选项仅适用于支持设置目录时间戳的移植版本
（目前为 ATheOS、BeOS、MacOS、OS/2、Unix、VMS、Win32；
对于其他 \fIunzip\fP 移植版本，\fB\-D\fP 无效）。
重复的选项 \fB\-DD\fP 强制抑制对所有提取条目
（文件和目录）的时间戳恢复。
此选项导致所有提取条目的时间戳被设置为当前时间。
.IP
在 VMS 上，此选项的默认设置为 \fB\-D\fP 以与 BACKUP 的行为
保持一致：文件时间戳被恢复，提取的目录时间戳保留为当前时间。
要启用目录时间戳的恢复，应指定否定形式的选项 \fB\--D\fP。
在 VMS 上，\fB\-D\fP 选项禁用所有提取的 Zip 归档项的时间戳恢复。
（此处，命令行上的单个 \fB\-D\fP 与默认的 \fB\-D\fP 结合，
执行其他系统上显式 \fB\-DD\fP 所做的操作。）
.TP
.B \-E
[仅 MacOS] 在恢复操作期间显示 MacOS 额外字段的内容。
.TP
.B \-F
[仅 Acorn] 禁止从存储的文件名中移除 NFS 文件类型扩展名。
.TP
.B \-F
[支持带嵌入逗号的长文件名的非 Acorn 系统，
且仅当编译时定义了 ACORN_FTYPE_NFS 时]
将 ACORN RISC OS 额外字段块中的文件类型信息转换为
NFS 文件类型扩展名，并将其附加到提取文件的名称上。
（当存储的文件名看起来已经附加了 NFS 文件类型扩展名时，
它会被额外字段中的信息替换。）
.TP
.B \-i
[仅 MacOS] 忽略存储在 MacOS 额外字段中的文件名。
而是使用条目头通用部分中存储的最兼容的文件名。
.TP
.B \-j
废弃路径。不重新创建归档的目录结构；
所有文件都被放置在提取目录中（默认情况下为当前目录）。
.TP
.B \-J
[仅 BeOS] 废弃文件属性。
不恢复文件的 BeOS 文件属性，仅恢复文件数据。
.TP
.B \-J
[仅 MacOS] 忽略 MacOS 额外字段。
跳过所有 Macintosh 特定信息。
数据分支和资源分支作为单独的文件恢复。
.TP
.B \-K
[AtheOS, BeOS, Unix 仅] 保留 SUID/SGID/Tacky 文件属性。
没有此标志时，出于安全原因会清除这些属性位。
.TP
.B \-L
将来自仅大写操作系统或文件系统的任何文件名转换为小写。
（这是 5.11 版本之前 \fIunzip\fP 的默认行为；
新的默认行为与旧版本使用 \fB\-U\fP 选项时的行为相同，
该选项现已过时并将在未来版本中移除。）
根据归档程序的不同，在单大小写文件系统
（VMS、旧的 MS-DOS FAT 等）下归档的文件可能以全大写名称存储；
当提取到保留大小写的文件系统（如 OS/2 HPFS）
或区分大小写的文件系统（如 Unix）时，
这可能会难看或不方便。
默认情况下，\fIunzip\fP 完全按照存储的方式列出和提取这些文件名
（截断、不支持的字符转换等除外）；
此选项导致来自某些系统的所有文件名被转换为小写。
\fB\-LL\fP 选项强制将所有文件名转换为小写，
无论原始文件系统如何。
.TP
.B \-M
将所有输出通过内部分页器传输，类似于 Unix \fImore\fP(1) 命令。
在一屏输出结束时，\fIunzip\fP 暂停并显示
``\-\-More\-\-'' 提示；
按 Enter（Return）键或空格键可查看下一屏。
按 ``q'' 键可以终止 \fIunzip\fP，
在某些系统上按 Enter/Return 键也可以。
与 Unix \fImore\fP(1) 不同，没有前向搜索或编辑功能。
此外，\fIunzip\fP 不会注意到长行是否在屏幕边缘自动换行，
这实际上会导致打印两行或更多行，
并且某些文本在查看之前可能已滚动到屏幕顶部之外。
在某些系统上，屏幕上的可用行数无法检测，
在这种情况下 \fIunzip\fP 假定高度为 24 行。
.TP
.B \-n
从不覆盖现有文件。
如果文件已存在，则跳过该文件的提取而不提示。
默认情况下，\fIunzip\fP 在提取任何已存在的文件之前会进行询问；
用户可以选择仅覆盖当前文件、覆盖所有文件、
跳过提取当前文件、跳过提取所有现有文件、
或重命名当前文件。
.TP
.B \-N
[Amiga] 将文件注释提取为 Amiga 文件注释。
文件注释使用 \fIzip\fP(1L) 的 -c 选项创建，
或使用 Amiga 移植版 \fIzip\fP(1L) 的 -N 选项创建，
后者将文件注释存储为注释。
.TP
.B \-o
覆盖现有文件而不提示。
这是一个危险的选项，请谨慎使用。
（但它经常与 \fB\-f\fP 一起使用，
并且是在 OS/2 下覆盖目录 EA 的唯一方法。）
.IP \fB\-P\fP\ \fIpassword\fP
使用 \fIpassword\fP 解密加密的 zip 文件条目（如果有）。
\fB这是不安全的！\fP
许多多用户操作系统提供方法让任何用户看到其他用户的当前命令行；
即使在单机系统上，也始终存在从背后窥视的威胁。
将明文密码作为命令行的一部分存储在自动化脚本中更是糟糕。
尽可能使用不回显的交互式提示来输入密码。
（在安全性真正重要的地方，请使用强加密，例如
Pretty Good Privacy，而不是标准 zip 文件工具提供的
相对较弱的加密。）
.TP
.B \-q
安静地执行操作（\fB\-qq\fP = 更安静）。
通常 \fIunzip\fP 打印其正在提取或测试的文件名、
提取方法、归档中可能存储的任何文件或 zip 文件注释，
以及可能在完成每个归档时的摘要。
\fB\-q\fP[\fBq\fP] 选项抑制部分或全部这些消息的打印。
.TP
.B \-s
[OS/2, NT, MS-DOS] 将文件名中的空格转换为下划线。
由于所有 PC 操作系统都允许文件名中的空格，
\fIunzip\fP 默认保持文件名中的空格不变
（例如，``\fCEA DATA.\ SF\fR''）。
但这可能很麻烦，特别是 MS-DOS 不能很好地支持文件名中的空格。
将空格转换为下划线可以在某些情况下消除这种麻烦。
.TP
.B \-S
[VMS] 将文本文件（\fB\-a\fP、\fB\-aa\fP）
转换为 Stream_LF 记录格式，
而不是文本文件默认的可变长度记录格式。
（Stream_LF 是 VMS \fIunzip\fP 的默认记录格式。
除非请求转换（\fB\-a\fP、\fB\-aa\fP 和/或
\fB\-b\fP、\fB\-bb\fP）或正在处理 VMS 特定条目，
否则将应用此格式。）
.TP
.B \-U
[仅 UNICODE_SUPPORT] 修改或禁用 UTF-8 处理。
当 UNICODE_SUPPORT 可用时，\fB\-U\fP 选项强制 \fIunzip\fP
将 UTF-8 编码文件名中的非 ASCII 字符转义为 ``#Uxxxx''
（对于 UCS-2 字符，或需要 3 个八位字节的 Unicode 码点
使用 ``#Lxxxxxx''）。
此选项主要用于调试目的，
当相当新的 UTF-8 支持被怀疑会搞乱提取的文件名时。
.IP
\fB\-UU\fP 选项允许完全禁用 UTF-8 编码文件名的识别。
\fIunzip\fP 中的文件名编码处理回退到以前版本的行为。
.IP
[旧的、已过时的用法] 如果文件名是在 MS-DOS、VMS 等下创建的，
则保持大写。请参见上面的 \fB\-L\fP。
.TP
.B \-V
保留（VMS）文件版本号。
VMS 文件可以以 \fCfile.ext;##\fR 格式存储版本号。
默认情况下，``\fC;##\fR'' 版本号被去除，
但此选项允许保留它们。
（在将文件名限制为特别短长度的文件系统上，
无论此选项如何，版本号都可能被截断或去除。）
.TP
.B \-W
[仅当 WILD_STOP_AT_DIR 编译时选项启用时]
修改模式匹配例程，
使 `?'（单字符通配符）和 `*'（多字符通配符）
都不匹配目录分隔符 `/'。
（两个字符的序列 ``**'' 充当多字符通配符，
在其匹配的字符中包含目录分隔符。）示例：
.PP
.EX
    "*.c" 匹配 "foo.c" 但不匹配 "mydir/foo.c"
    "**.c" 同时匹配 "foo.c" 和 "mydir/foo.c"
    "*/*.c" 匹配 "bar/foo.c" 但不匹配 "baz/bar/foo.c"
    "??*/*" 匹配 "ab/foo" 和 "abc/foo"
           但不匹配 "a/foo" 或 "a/b/foo"
.EE
.IP
此修改后的行为等效于 UnZip 的某些受支持目标操作系统
（例如 Acorn RISC OS）的 shell 使用的模式匹配风格。
在 Zip 归档的内部目录分隔符 `/' 被允许作为
本机操作系统文件名中的常规字符的系统上，此选项可能不可用。
（目前，在大多数移植版本中，UnZip 对通配符 zip 文件规格和
zip 条目选择模式使用相同的模式匹配规则。
对于允许 `/' 作为常规文件名字符的系统，
-W 选项在通配符 zip 文件规格上可能无法按预期工作。）
.TP
.B \-X
[VMS, Unix, OS/2, NT, Tandem]
在 VMS 下恢复所有者/保护信息（UIC 和 ACL 条目），
或在 Unix 下恢复用户和组信息（UID/GID），
或在某些启用网络的 OS/2 版本
（带有 IBM LAN Server/Requester 3.0 到 5.0 的 Warp Server；
带有 IBM Peer 1.0 的 Warp Connect）下恢复访问控制列表（ACL），
或在 Windows NT 下恢复安全 ACL。
在大多数情况下，这需要特殊的系统权限，
并且在 NT 下加倍选项（\fB\-XX\fP）
指示 \fIunzip\fP 使用特权进行提取；
但在 Unix 下，属于多个组的用户可以恢复其中任何组拥有的文件，
只要用户 ID 与用户自己的 ID 匹配。
请注意，普通文件属性始终会被恢复——
此选项仅适用于某些操作系统上可选的额外所有权信息。
[NT 的访问控制列表似乎与 OS/2 的 ACL 不是特别兼容，
因此不尝试跨平台的访问权限可移植性。
目前尚不清楚在什么条件下这会是有用的。]
.TP
.B \-Y
[VMS] 将以 ``.nnn'' 结尾的归档文件名
（其中 ``nnn'' 是十进制数字）视为 VMS 版本号（``;nnn''）。
（默认将它们视为文件类型。）示例：
.EX
     "a.b.3" -> "a.b;3".
.EE
.TP
.B \-$
.\" Amiga support possible eventually, but not yet
[MS-DOS, OS/2, NT] 如果提取介质是可移动的（例如软盘），
则恢复卷标。
加倍选项（\fB\-$$\fP）也允许标记固定介质（硬盘）。
默认情况下，卷标被忽略。
.IP \fB\-/\fP\ \fIextensions\fP
[仅 Acorn] 覆盖 Unzip$Ext 环境变量提供的扩展名列表。
提取时，与此扩展名列表中某一项匹配的文件名扩展名
会被交换到提取文件的基本名称之前。
.TP
.B \-:
[除 Acorn、VM/CMS、MVS、Tandem 外]
允许将归档成员提取到当前"提取根文件夹"之外的位置。
出于安全原因，\fIunzip\fP 通常从提取的文件名中
移除"父目录"路径组件（``../''）。
此安全功能（5.50 版本的新功能）防止 \fIunzip\fP 意外将文件写入
活动提取文件夹树头之外的"敏感"区域。
\fB\-:\fP 选项让 \fIunzip\fP 切换回以前更宽松的行为，
以允许精确提取使用 ``../'' 组件在当前提取文件夹级别
创建多个目录树的（较旧）归档。
此选项不允许显式写入根目录（``/''）。
要实现这一点，需要将提取目标文件夹设置为根目录
（例如 \fB\-d / \fP）。
然而，当指定 \fB\-:\fP 选项时，
仍然可以通过在 zip 归档中指定足够多的 ``../'' 路径组件
来隐式写入根目录。
请格外谨慎地使用此选项。
.TP
.B \-^
[仅 Unix] 允许提取的 ZIP 归档条目名称中包含控制字符。
在 Unix 上，文件名可以包含任何（8 位）字符代码，
但有两个例外：'/'（目录分隔符）和 NUL（0x00，C 字符串终止指示符），
除非特定的文件系统有更严格的约定。
通常，这允许在文件名中嵌入 ASCII 控制字符
（甚至复杂的控制序列），至少在"原生"Unix 文件系统上如此。
然而，使用这种 Unix "特性"可能非常可疑。
文件名中的嵌入控制字符在屏幕上显示时可能产生讨厌的副作用，
如果没有足够的过滤。
并且，对于普通用户来说，处理此类文件名可能很困难
（例如，尝试指定打开、复制、移动或删除操作时）。
因此，\fIunzip\fP 默认应用过滤器，
从提取的文件名中移除潜在危险的控制字符。
\fB-^\fP 选项允许在极少数情况下有意恢复嵌入的文件名控制字符时
覆盖此过滤器。
.TP
.B \-2
[VMS] 强制无条件地将文件名转换为 ODS2 兼容名称。
默认是利用目标文件系统，
在 ODS5 目标文件系统上保留大小写和扩展文件名；
在 ODS2 目标文件系统上应用 ODS2 兼容文件名过滤。
.PD
.\" =========================================================================
.SH 环境变量选项 (ENVIRONMENT OPTIONS)
\fIunzip\fP 的默认行为可以通过放置在环境变量中的选项进行修改。
这可以通过任何选项完成，但可能最有用的是 \fB\-a\fP、\fB\-L\fP、
\fB\-C\fP、\fB\-q\fP、\fB\-o\fP 或 \fB\-n\fP 修饰符：
使 \fIunzip\fP 默认自动转换文本文件、
使其将大写系统的文件名转换为小写、
使其不区分大小写地匹配名称、使其更安静、
或使其在提取时始终覆盖或从不覆盖文件。
例如，要使 \fIunzip\fP 尽可能安静，只报告错误，
可以使用以下命令之一：
.TP
  Unix Bourne shell:
UNZIP=\-qq; export UNZIP
.TP
  Unix C shell:
setenv UNZIP \-qq
.TP
  OS/2 或 MS-DOS:
set UNZIP=\-qq
.TP
  VMS（引号用于\fIlowercase\fP）:
define UNZIP_OPTS "\-qq"
.PP
环境选项实际上被视为与任何其他命令行选项一样，
只是它们实际上是命令行上的第一个选项。
要覆盖环境选项，可以使用"减号运算符"来移除它。
例如，要覆盖上面示例中的某个安静标志，请使用命令：
.PP
.EX
unzip \-\-q[\fIother options\fP] zipfile
.EE
.PP
第一个连字符是正常的开关字符，第二个是减号，作用于 q 选项。
因此这里的效果是取消一个单位的安静度。
要取消两个安静标志，可以使用两个（或更多）减号：
.PP
.EX
unzip \-t\-\-q zipfile
unzip \-\-\-qt zipfile
.EE
.PP
（两者等效）。这看起来可能笨拙或令人困惑，但它是相当直观的：
只需忽略第一个连字符并继续操作。
它也与 Unix \fInice\fP(1) 的行为一致。
.PP
正如上述示例所建议的，默认变量名对于 VMS 是 UNZIP_OPTS
（否则用于将 \fIunzip\fP 安装为外部命令的符号
会与环境变量混淆），对于所有其他操作系统是 UNZIP。
为了与 \fIzip\fP(1L) 兼容，也接受 UNZIPOPT（不要问为什么）。
但是，如果同时定义了 UNZIP 和 UNZIPOPT，则 UNZIP 优先。
\fIunzip\fP 的诊断选项（不带 zip 文件名的 \fB\-v\fP）
可用于检查所有四个可能的 \fIunzip\fP 和 \fIzipinfo\fP
环境变量的值。
.PP
时区变量（TZ）应根据本地时区设置，
以便 \fB\-f\fP 和 \fB\-u\fP 正确运行。
有关详细信息，请参见上面 \fB\-f\fP 的描述。
此变量也可能是正确设置提取文件时间戳所必需的。
\fIunzip\fP 的 WIN32（Win9x/ME/NT4/2K/XP/2K3）移植版本
从注册表中获取时区配置，假设在控制面板中正确设置。
此移植版本忽略 TZ 变量。
.PD
.\" =========================================================================
.SH 解密 (DECRYPTION)
Info-ZIP 软件完全支持加密归档，
但由于美国的出口限制，加/解密支持可能在您编译的二进制文件中被禁用。
然而，自 2000 年春季以来，美国出口限制已放宽，
我们的源码归档现在包含完整的加密代码。
如果您需要启用加密支持的二进制分发版，
请参见任何 Info-ZIP 源码或二进制分发版中的 ``WHERE'' 文件，
以了解美国境内外的位置。
.PP
某些编译版本的 \fIunzip\fP 可能不支持解密。
要检查某个版本是否支持加密，
可以尝试测试或提取加密归档，
或者检查 \fIunzip\fP 的诊断屏幕
（请参见上面的 \fB\-v\fP 选项）中是否有
``\fC[decryption]\fR'' 作为特殊编译选项之一。
.PP
如上所述，\fB\-P\fP 选项可用于在命令行上提供密码，
但以牺牲安全性为代价。
首选的解密方法只是正常提取；
如果 zip 文件成员是加密的，
\fIunzip\fP 将提示输入密码且不回显键入内容。
\fIunzip\fP 会继续使用相同的密码，只要它看起来有效——
通过测试每个文件上的 12 字节头部。
正确的密码将始终通过头部检查，
但不正确的密码也有 1/256 的概率通过。
（这是 PKWARE zip 文件格式的安全特性；
它有助于防止暴力攻击，
否则攻击者可能仅通过测试头部就获得巨大的速度优势。）
如果给出了不正确的密码但仍然通过了头部测试，
那么要么生成提取数据的 CRC 不正确，
要么 \fIunzip\fP 在提取期间失败，
因为"解密"的字节不构成有效的压缩数据流。
.PP
如果第一个密码在某个文件上未能通过头部检查，
\fIunzip\fP 将提示输入另一个密码，
依此类推，直到所有文件都被提取。
如果不知道密码，输入空密码（即仅回车或 "Enter"）
被视为跳过所有进一步提示的信号。
之后只会提取归档中的未加密文件。
（实际上，这不完全正确；
旧版本的 \fIzip\fP(1L) 和 \fIzipcloak\fP(1L) 允许空密码，
因此 \fIunzip\fP 会检查每个加密文件，看空密码是否有效。
这可能导致"误报"和提取错误，如上所述。）
.PP
使用 8 位密码加密的归档（例如，带有重音欧洲字符的密码）
可能在系统和/或其他归档程序之间不可移植。
这个问题源于对此类字符使用多种编码方法，
包括 Latin-1（ISO 8859-1）和 OEM 代码页 850。
DOS \fIPKZIP\fP 2.04g 使用 OEM 代码页；
Windows \fIPKZIP\fP 2.50 使用 Latin-1
（因此与 DOS \fIPKZIP\fP 不兼容）；
Info-ZIP 在 DOS、OS/2 和 Win3.x 移植版上使用 OEM 代码页，
但在其他所有地方使用 ISO 编码（Latin-1 等）；
Nico Mak 的 \fIWinZip\fP 6.x 根本不允许 8 位密码。
\fIUnZip\fP 5.3（或更新版本）尝试首先使用默认字符集
（例如 Latin-1），然后使用备选字符集（例如 OEM 代码页）
测试密码。在 EBCDIC 系统上，如果两者都失败，
将最后尝试 EBCDIC 编码。
（在非 EBCDIC 系统上不测试 EBCDIC，
因为没有已知的归档程序使用 EBCDIC 编码进行加密。）
不支持除 Latin-1 之外的 ISO 字符编码。
\fIUnZip\fP 6.0 中新增的（部分）Unicode（或 UTF-8）支持
尚未适应 \fIunzip\fP 中的加密密码处理。
在使用 UTF-8 作为本地字符编码的系统上，
\fIunzip\fP 简单地尝试使用本地 UTF-8 编码密码进行解密；
内置的尝试以转换后编码检查密码的功能尚未适应 UTF-8 支持，
因此将失败。
.PD
.\" =========================================================================
.SH 示例 (EXAMPLES)
使用 \fIunzip\fP 将归档 \fIletters.zip\fP 的所有成员
提取到当前目录及其子目录中，必要时创建任何子目录：
.PP
.EX
unzip letters
.EE
.PP
仅将 \fIletters.zip\fP 的所有成员提取到当前目录：
.PP
.EX
unzip -j letters
.EE
.PP
测试 \fIletters.zip\fP，
仅打印指示归档是否正常的摘要消息：
.PP
.EX
unzip -tq letters
.EE
.PP
测试当前目录中的\fI所有\fP zip 文件，仅打印摘要：
.PP
.EX
unzip -tq \e*.zip
.EE
.PP
（反斜杠前缀的星号仅在 shell 展开通配符时需要，
如在 Unix 中；双引号也可以替代使用，如以下源码示例。）
\ \ 将 \fIletters.zip\fP 中所有名称以 \fI.tex\fP 结尾的成员
提取到标准输出，自动转换为本地行尾约定
并将输出通过管道传送到 \fImore\fP(1)：
.PP
.EX
unzip \-ca letters \e*.tex | more
.EE
.PP
将二进制文件 \fIpaper1.dvi\fP 提取到标准输出
并通过管道传送到打印程序：
.PP
.EX
unzip \-p articles paper1.dvi | dvips
.EE
.PP
将所有 FORTRAN 和 C 源文件——*.f、*.c、*.h 和 Makefile——
提取到 /tmp 目录：
.PP
.EX
unzip source.zip "*.[fch]" Makefile -d /tmp
.EE
.PP
（双引号仅在 Unix 中且仅在通配符展开开启时需要）。
要提取所有 FORTRAN 和 C 源文件，无论大小写
（例如，*.c 和 *.C，以及任何 makefile、Makefile、
MAKEFILE 或类似文件）：
.PP
.EX
unzip \-C source.zip "*.[fch]" makefile -d /tmp
.EE
.PP
要提取任何此类文件但将任何大写 MS-DOS 或 VMS 名称转换为小写
并将所有文件的行尾转换为本地标准
（不考虑任何可能标记为"二进制"的文件）：
.PP
.EX
unzip \-aaCL source.zip "*.[fch]" makefile -d /tmp
.EE
.PP
仅提取当前目录中已存在的文件的更新版本，不询问
（注意：小心在一个时区解压在另一个时区创建的 zip 文件——
由 Zip 2.1 或更高版本以外的程序创建的 ZIP 归档不包含时区信息，
来自东部时区的"更新"文件实际上可能更旧）：
.PP
.EX
unzip \-fo sources
.EE
.PP
提取当前目录中已存在的文件的更新版本
并创建任何尚不存在的文件
（与前一个示例相同的注意事项）：
.PP
.EX
unzip \-uo sources
.EE
.PP
显示诊断屏幕，显示哪些 \fIunzip\fP 和 \fIzipinfo\fP 选项
存储在环境变量中、是否编译了解密支持、
编译 \fIunzip\fP 时使用的编译器等等：
.PP
.EX
unzip \-v
.EE
.PP
在最后五个示例中，假设 UNZIP 或 UNZIP_OPTS 设置为 -q。
要进行单一级别的安静列表：
.PP
.EX
unzip \-l file.zip
.EE
.PP
要进行双倍安静级别的列表：
.PP
.EX
unzip \-ql file.zip
.EE
.PP
（注意，通常不需要 ``\fC.zip\fR''。）要进行标准列表：
.PP
.EX
unzip \-\-ql file.zip
.EE
或
.EX
unzip \-l\-q file.zip
.EE
或
.EX
unzip \-l\-\-q file.zip
.EE
\fR（选项中的额外减号没有坏处。）
.PD
.\" =========================================================================
.SH 提示 (TIPS)
当前维护者作为一个懒惰的人，
发现定义一对别名非常有用：\fCtt\fR 用于
``\fCunzip \-tq\fR''，
\fCii\fR 用于 ``\fCunzip \-Z\fR''
（或 ``\fCzipinfo\fR''）。
然后可以简单地输入 ``\fCtt zipfile\fR'' 来测试归档，
这是一个值得养成习惯的做法。
如果运气好，\fIunzip\fP 将报告
``\fCNo errors detected in compressed data of zipfile.zip\fR''，
然后可以松一口气。
.PP
维护者还发现将 UNZIP 环境变量设置为 ``\fC\-aL\fR'' 很有用，
并且很想也添加 ``\fC\-C\fR''。
他的 ZIPINFO 变量设置为 ``\fC\-z\fR''。
.PD
.\" =========================================================================
.SH 诊断 (DIAGNOSTICS)
退出状态（或错误级别）近似于 PKWARE 定义的退出代码，
并取以下值，VMS 除外：
.RS
.IP 0
正常；未检测到错误或警告。
.IP 1
遇到一个或多个警告错误，但处理仍然成功完成。
这包括其中有一个或多个文件由于不支持的压缩方法
或使用未知密码加密而被跳过的 zip 文件。
.IP 2
检测到 zip 文件格式中的一般错误。
处理可能仍然成功完成；
其他归档程序创建的某些损坏的 zip 文件有简单的解决方法。
.IP 3
检测到 zip 文件格式中的严重错误。处理可能立即失败。
.IP 4
\fIunzip\fP 在程序初始化期间无法为一个或多个缓冲区分配内存。
.IP 5
\fIunzip\fP 无法分配内存或无法获得 tty 来读取解密密码。
.IP 6
\fIunzip\fP 在解压缩到磁盘期间无法分配内存。
.IP 7
\fIunzip\fP 在内存解压缩期间无法分配内存。
.IP 8
[当前未使用]
.IP 9
未找到指定的 zip 文件。
.IP 10
在命令行上指定了无效的选项。
.IP 11
未找到匹配的文件。
.IP 12
包含重叠组件的无效 zip 文件（可能的 zip-bomb）。
可以通过使用 UNZIP_DISABLE_ZIPBOMB_DETECTION=TRUE
环境变量禁用 zip-bomb 检查。
.IP 50
提取期间磁盘已满（或曾经满）。
.IP 51
过早遇到 ZIP 归档的结尾。
.IP 80
用户通过 control-C（或类似方式）过早中止了 \fIunzip\fP。
.IP 81
由于不支持的压缩方法或不支持的解密，
一个或多个文件的测试或提取失败。
.IP 82
由于错误的解密密码，未找到任何文件。
（但如果至少有一个文件成功处理，则退出状态为 1。）
.RE
.PP
VMS 将标准 Unix（或 PC）返回值解释为其他看起来更可怕的东西，
因此 \fIunzip\fP 改为将它们映射为 VMS 风格的状态代码。
当前的映射如下：正常退出为 1（成功），
警告错误为 0x7fff0001，
所有其他错误为（0x7fff000? + 16*normal_unzip_exit_status），
其中 `?' 对于 \fIunzip\fP 值 2、9-11 和 80-82 为 2（错误），
对于其余值（3-8、50、51）为 4（致命错误）。
此外，还有一个编译选项可以扩展此行为：
定义 RETURN_CODES 将产生关于错误状态含义的人类可读解释。
.PD
.\" =========================================================================
.SH 错误 (BUGS)
多部分归档尚不支持，除非与 \fIzip\fP 结合使用。
（所有部分必须按顺序连接在一起，
然后对连接的归档执行 ``\fCzip \-F\fR''
（对于 \fIzip 2.x\fP）或 ``\fCzip \-FF\fR''
（对于 \fIzip 3.x\fP）以"修复"它。
此外，\fIzip 3.0\fP 及更高版本可以使用
``\fCzip \-s\- inarchive -O outarchive\fR''
将多部分（拆分）归档组合成单个文件归档。
更多信息请参见 \fIzip 3\fP 手册页。）
这将在下一个主要版本中修正。
.PP
从标准输入读取归档尚不支持，
除非使用 \fIfunzip\fP
（并且此时只能提取归档的第一个成员）。
.PP
使用 8 位密码加密的归档
（例如，带有重音欧洲字符的密码）
可能在系统和/或其他归档程序之间不可移植。
请参见上面 \fBDECRYPTION\fP 中的讨论。
.PP
\fIunzip\fP 的 \fB\-M\fP（"more"）选项试图考虑长行的自动换行。
然而，代码可能无法检测到正确的换行位置。
首先，TAB 字符（和类似的控制序列）未被考虑，
它们被当作普通可打印字符处理。
其次，根据实际的系统/操作系统移植版本，
\fIunzip\fP 可能无法检测到真实的屏幕几何尺寸，
而是依赖于"常用"的默认尺寸。
正确处理制表符需要实现对输出控制台上实际制表符设置的查询。
.PP
除 Unix 外，存储目录的日期、时间和权限不会被恢复。
（在 Windows NT 及后续版本上，现在可以恢复时间戳。）
.PP
[MS-DOS] 从有缺陷的软盘上的归档中提取或测试文件时，
如果从 DOS 的 "Abort, Retry, Fail?" 消息中选择了 "Fail" 选项，
旧版本的 \fIunzip\fP 可能会挂起系统，需要重新启动。
此问题似乎已修复，但仍可使用 control-C（或 control-Break）
终止 \fIunzip\fP。
.PP
在 DEC Ultrix 下，\fIunzip\fP 有时会在长 zip 文件上失败
（CRC 错误，并不总是可重现）。
这显然是由于硬件错误（缓存内存）
或操作系统错误（页面错误处理不当？）所致。
由于 Ultrix 已被放弃，转而使用 Digital Unix（OSF/1），
这可能不再是问题。
.PP
[Unix] Unix 特殊文件，如 FIFO 缓冲区（命名管道）、
块设备和字符设备不会被恢复，
即使它们以某种方式表示在 zip 文件中；
硬链接文件也不会被重新链接。
基本上，\fIunzip\fP 恢复的唯一文件类型是普通文件、
目录和符号（软）链接。
.PP
[OS/2] 现有目录的扩展属性仅在给出 \fB\-o\fP
（"覆盖所有"）选项时更新。
这是操作系统的限制；
因为目录只关联有创建时间，\fIunzip\fP 无法确定存储的属性
比磁盘上的更新还是更旧。
在实践中，这可能意味着需要两遍方法：
首先正常解包归档（有或没有刷新/更新现有文件），
然后仅覆盖目录条目
（例如，``\fCunzip -o foo */\fR''）。
.PP
[VMS] 当提取到另一个目录时，
\fB\-d\fP 选项只接受 \fI[.foo]\fP 语法；
简单的 Unix \fIfoo\fP 语法被静默忽略
（较不常见的 VMS \fIfoo.dir\fP 语法也是如此）。
.PP
[VMS] 当要提取的文件已存在时，
\fIunzip\fP 的询问只允许跳过、覆盖或重命名；
还应该有为文件创建新版本的选项。
实际上，"覆盖"选择确实会创建新版本；
旧版本不会被覆盖或删除。
.PD
.\" =========================================================================
.SH 参见 (SEE ALSO)
\fIfunzip\fP(1L), \fIzip\fP(1L), \fIzipcloak\fP(1L),
\fIzipgrep\fP(1L), \fIzipinfo\fP(1L), \fIzipnote\fP(1L),
\fIzipsplit\fP(1L)
.PD
.\" =========================================================================
.SH 网址 (URL)
Info-ZIP 主页目前位于
.EX
\fChttp://www.info-zip.org/pub/infozip/\fR
.EE
或
.EX
\fCftp://ftp.info-zip.org/pub/infozip/\fR .
.EE
.PD
.\" =========================================================================
.SH 作者 (AUTHORS)
Info-ZIP 的主要作者（当前 Zip-Bugs 工作组半活跃成员）有：
Ed Gordon（Zip、一般维护、共享代码、Zip64、Win32、Unix、Unicode）；
Christian Spieler（UnZip 维护协调、VMS、MS-DOS、Win32、
共享代码、一般 Zip 和 UnZip 集成与优化）；
Onno van der Linden（Zip）；
Mike White（Win32、Windows GUI、Windows DLLs）；
Kai Uwe Rommel（OS/2、Win32）；
Steven M. Schweda（VMS、Unix、新功能支持）；
Paul Kienitz（Amiga、Win32、Unicode）；
Chris Herborth（BeOS、QNX、Atari）；
Jonathan Hudson（SMS/QDOS）；
Sergio Monesi（Acorn RISC OS）；
Harald Denker（Atari、MVS）；
John Bush（Solaris、Amiga）；
Hunter Goatley（VMS、Info-ZIP 站点维护）；
Steve Salisbury（Win32）；
Steve Miller（Windows CE GUI）；
Johnny Lee（MS-DOS、Win32、Zip64）；
以及 Dave Smith（Tandem NSK）。
.PP
以下人员是 Info-ZIP 开发组的前成员，
并对当前代码的关键部分做出了重大贡献：
Greg ``Cave Newt'' Roelofs（UnZip、unshrink 解压缩）；
Jean-loup Gailly（deflate 压缩）；
Mark Adler（inflate 解压缩、fUnZip）。
.PP
Info-ZIP 的 unzip 代码所基于的原始 unzip 代码的作者
是 Samuel H. Smith；
Carl Mascott 进行了第一次 Unix 移植；
David P. Kirschbaum 在 Info-ZIP 的早期组织和领导了它，
Keith Petersen 在 WSMR-SimTel20 托管了原始邮件列表。
UnZip 的贡献者完整列表已经相当庞大；
请参考 UnZip 源码分发版中的 CONTRIBS 文件
以获取相对完整的版本。
.PD
.\" =========================================================================
.SH 版本 (VERSIONS)
.ta \w'vx.xxnn'u +\w'fall 1989'u+3n
.PD 0
.IP "v1.2\t15 Mar 89" \w'\t\t'u
Samuel H. Smith
.IP "v2.0\t\ 9 Sep 89"
Samuel H. Smith
.IP "v2.x\tfall 1989"
许多 Usenet 贡献者
.IP "v3.0\t\ 1 May 90"
Info-ZIP（DPK，整合者）
.IP "v3.1\t15 Aug 90"
Info-ZIP（DPK，整合者）
.IP "v4.0\t\ 1 Dec 90"
Info-ZIP（GRR，维护者）
.IP "v4.1\t12 May 91"
Info-ZIP
.IP "v4.2\t20 Mar 92"
Info-ZIP（Zip-Bugs 子组，GRR）
.IP "v5.0\t21 Aug 92"
Info-ZIP（Zip-Bugs 子组，GRR）
.IP "v5.01\t15 Jan 93"
Info-ZIP（Zip-Bugs 子组，GRR）
.IP "v5.1\t\ 7 Feb 94"
Info-ZIP（Zip-Bugs 子组，GRR）
.IP "v5.11\t\ 2 Aug 94"
Info-ZIP（Zip-Bugs 子组，GRR）
.IP "v5.12\t28 Aug 94"
Info-ZIP（Zip-Bugs 子组，GRR）
.IP "v5.2\t30 Apr 96"
Info-ZIP（Zip-Bugs 子组，GRR）
.IP "v5.3\t22 Apr 97"
Info-ZIP（Zip-Bugs 子组，GRR）
.IP "v5.31\t31 May 97"
Info-ZIP（Zip-Bugs 子组，GRR）
.IP "v5.32\t\ 3 Nov 97"
Info-ZIP（Zip-Bugs 子组，GRR）
.IP "v5.4\t28 Nov 98"
Info-ZIP（Zip-Bugs 子组，SPC）
.IP "v5.41\t16 Apr 00"
Info-ZIP（Zip-Bugs 子组，SPC）
.IP "v5.42\t14 Jan 01"
Info-ZIP（Zip-Bugs 子组，SPC）
.IP "v5.5\t17 Feb 02"
Info-ZIP（Zip-Bugs 子组，SPC）
.IP "v5.51\t22 May 04"
Info-ZIP（Zip-Bugs 子组，SPC）
.IP "v5.52\t28 Feb 05"
Info-ZIP（Zip-Bugs 子组，SPC）
.IP "v6.0\t20 Apr 09"
Info-ZIP（Zip-Bugs 子组，SPC）
.PD
.\" =========================================================================
.SH "[中文版维护人]"
.B Aurolystant
.SH "[中文版最新更新]"
.BR 2026.07.13
.SH "[中国 Linux 论坛中文手册页翻译计划]"
.BI https://github.com/man-pages-zh/manpages-zh
