'\" t
.\"     Title: whereis
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.26
.\"      Date: 2026-06-16
.\"    Manual: 用户命令
.\"    Source: util-linux 2.42.2
.\"  Language: Chinese (Simplified)
.\"
.TH "WHEREIS" "1" "2026-06-16" "util\-linux 2.42.2" "用户命令"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "名称"
whereis \- 定位命令的二进制文件、源代码和手册页文件
.SH "概述"
.sp
\fBwhereis\fP [选项] [\fB\-BMS\fP \fI目录\fP.\|.\|. \fB\-f\fP] \fI名称\fP.\|.\|.
.SH "描述"
.sp
\fBwhereis\fP 定位指定命令名称的二进制、源文件和手册文件。提供的名称会首先去除前导路径名组件。对于源代码控制产生的 \fBs.\fP 前缀也会处理。\fBwhereis\fP 然后尝试在标准 Linux 位置以及 \fB$PATH\fP 和 \fB$MANPATH\fP 指定的位置中定位所需的程序。
.sp
搜索限制（选项 \fB\-b\fP、\fB\-m\fP 和 \fB\-s\fP）是累积的，并应用于命令行中后续的 \fI名称\fP 模式。任何新的搜索限制都会重置搜索掩码。例如，
.RS 3
.ll -.6i
.sp
\fBwhereis \-bm ls tr \-m gcc\fP
.br
.RE
.ll
.sp
表示搜索 "ls" 和 "tr" 的二进制文件和手册页，但只搜索 "gcc" 的手册页。
.SH "选项"
.sp
\fB\-b\fP — 搜索二进制文件。
.sp
\fB\-m\fP — 搜索手册页。
.sp
\fB\-s\fP — 搜索源代码。
.sp
\fB\-u\fP — 仅显示具有异常条目的命令名称。
.sp
\fB\-B\fP \fI列表\fP — 限制搜索二进制文件的目录（以空白字符分隔的列表）。
.sp
\fB\-M\fP \fI列表\fP — 限制搜索手册页和 Info 文档的目录。
.sp
\fB\-S\fP \fI列表\fP — 限制搜索源代码的目录。
.sp
\fB\-f\fP — 终止目录列表并标志文件名的开始。使用 \fB\-B\fP、\fB\-M\fP 或 \fB\-S\fP 选项时必须使用。
.sp
\fB\-l\fP — 输出 \fBwhereis\fP 正在使用的有效查找路径列表。
.sp
\fB\-g\fP — 将后续名称解释为 \fBglob(7)\fP 模式。
.sp
\fB\-h\fP, \fB\-\-help\fP — 显示帮助文本并退出。
.sp
\fB\-V\fP, \fB\-\-version\fP — 显示版本信息并退出。
.SH "环境变量"
.sp
\fBWHEREIS_DEBUG\fP=all — 启用调试输出。
.SH "报告错误"
.sp
请通过 \c
.URL "https://github.com/util\-linux/util\-linux/issues" "issue tracker" " 报告错误。"
.SH "获取"
.sp
\fBwhereis\fP 命令是 util\-linux 软件包的一部分，可从 \c
.URL "https://www.kernel.org/pub/linux/utils/util\-linux/" "Linux Kernel Archive" " 下载。"
.SH "[中文版最新更新]"
.BR 2026.07.12
.SH "[中文版维护人]"
.SH "[中国 Linux 论坛中文手册页翻译计划]"
.BI https://github.com/man-pages-zh/manpages-zh
